version: '3.8'

networks: 
  my_network: 
    driver: bridge

services:
  mysql:
    image: mysql:8

    container_name: "containerBD"

    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_USER: monitormind
      MYSQL_PASSWORD: urubu100
      MYSQL_DATABASE: MonitorMind
      networks: 
        - my_network
    volumes:
    - "./mysql-script/script.sql:/docker-entrypoint-initdb.d/1.sql"
  
  app:
    container_name: containerJar
    
    image: containerjar
    depends_on:
      - mysql
    tty: true
    volumes:
      - /:/host
    networks: 
      - my_network